### ISSUE TITLE
Please add option for disable pagination

### ISSUE THREAD

**Issue by s-kostyaev** [youngker/clj-opengrok#1]
Hi. Thank you for this cool project.
I would like to try implement another emacs interface for opengrok (based on clj-opengrok) with ivy & counsel as UI. So if you add this option I will use clj-opengrok for this. Long reply time without pagination does not matter because of ivy can add elements asyncronuosly (as you can see in counsel-ag).

**Comment by s-kostyaev** [comment]
My project will be like helm-gtags but with ivy instead of helm & opengrok instead of GNU Global.

**Comment by youngker** [comment]
Hi s-kostyaev
If there is no pagination, opengrok search need Loooong delay time before first matching result.
It is different "Long reply time" in your comment.
ex) android source has 65693 page for "test" search.
And you can search google with "lucene pagination performance"

**Comment by s-kostyaev** [comment]
I would like to enable this for search definitions & references only, not for FTS. I don't think that pagination must be disabled by default. Can you add command line argument for disable pagination?

**Comment by s-kostyaev** [comment]
> If there is no pagination, opengrok search need Loooong delay time before first matching result.

this is bad. I'll try to find another solution with enabled pagination. Thanks.
